# Generated by Django 4.2.3 on 2024-02-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='image',
            field=models.ImageField(default='default profile.jpg', upload_to='media'),
        ),
    ]
