# Generated by Django 4.2.3 on 2024-02-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_profile_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='image',
            field=models.ImageField(default='default cprofile.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
