# Generated by Django 4.2.3 on 2024-02-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_profile_model_bio_alter_profile_model_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
