# Generated by Django 4.2.3 on 2024-02-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_profile_model_bio_alter_profile_model_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='image',
            field=models.ImageField(default='default profile.jpg', upload_to='media'),
        ),
    ]
