# Generated by Django 4.2.3 on 2024-02-11 05:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0005_alter_profile_model_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_model',
            new_name='profile',
        ),
    ]
