# Generated by Django 4.2.3 on 2024-02-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', models.SlugField(max_length=100)),
                ('category_image', models.ImageField(upload_to='media')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
