# Generated by Django 4.2.3 on 2024-02-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='session_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'session_model',
                'verbose_name_plural': 'session',
            },
        ),
    ]
