# Generated by Django 4.2.3 on 2024-02-12 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_session_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
                ('cart_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.session_model')),
            ],
            options={
                'verbose_name': 'cartitem',
                'verbose_name_plural': 'cart',
            },
        ),
    ]
