# Generated by Django 4.2.3 on 2024-02-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_price',
            field=models.IntegerField(null=True),
        ),
    ]
